services:
  - type: web
    name: habeshabiz-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    region: ohio
    envVars:
      - key: APP_NAME
        value: HabeshaBiz
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-dark-glitter-b5kgbi9t-pooler.c-7.us-east-2.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: LOG_CHANNEL
        value: stderr
      - key: RUN_MIGRATIONS
        value: "true"
